spring:
  application:
    name: task.backend.ch
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
service:
  url: https://storage.googleapis.com/coding-session-rest-api/